baseURL = "https://joshgerdes.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Josh Gerdes"
theme = "joshgerdes"

enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "monokai"

[pagination]
  disableAliases = false
  pagerSize = 12

[params]
  author = "Josh Gerdes"
  description = "Founder of Lost Leaf Studio, developer, consultant, cyclist, soccer fan, nature enthusiast and lover of beer."
  recentPostsCount = 5
  summaryLength = 140

[params.social]
  gitHub = "joshgerdes"
  linkedin = "joshgerdes"
  twitter = "joshgerdes"
  instagram = "joshgerdes"
  email   = "josh@joshgerdes.com"

[permalinks]
  posts = "/:year/:month/:title"

[services]
  [services.googleAnalytics]
    id = "G-98ZZPG1KRR"

[taxonomies]
  tag = "tags"
